// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} source
 * @param {string} target
 * @returns {Promise.<Big>}
 */
export async function FastestLevenshtein_Distance(source, target) {
	// BEGIN USER CODE
	const {distance} = require('fastest-levenshtein')
	if(source == ""){
		throw new Error("source should not be empty")
	}
	if(target == ""){
		throw new Error("target should not be empty")
	}
	//console.info(distance(source, target));
	let distanceValue=distance(source, target)
	return distanceValue
	
	// END USER CODE
}
