// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fastestlevenshtein.proxies;

public class Levenshtein
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject levenshteinMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FastestLevenshtein.Levenshtein";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		String1("String1"),
		String2("String2"),
		LevenshteinType("LevenshteinType"),
		Distance("Distance"),
		Closest("Closest");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Levenshtein(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Levenshtein(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject levenshteinMendixObject)
	{
		if (levenshteinMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, levenshteinMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.levenshteinMendixObject = levenshteinMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Levenshtein.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static fastestlevenshtein.proxies.Levenshtein initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return fastestlevenshtein.proxies.Levenshtein.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fastestlevenshtein.proxies.Levenshtein initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fastestlevenshtein.proxies.Levenshtein(context, mendixObject);
	}

	public static fastestlevenshtein.proxies.Levenshtein load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fastestlevenshtein.proxies.Levenshtein.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of String1
	 */
	public final java.lang.String getString1()
	{
		return getString1(getContext());
	}

	/**
	 * @param context
	 * @return value of String1
	 */
	public final java.lang.String getString1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.String1.toString());
	}

	/**
	 * Set value of String1
	 * @param string1
	 */
	public final void setString1(java.lang.String string1)
	{
		setString1(getContext(), string1);
	}

	/**
	 * Set value of String1
	 * @param context
	 * @param string1
	 */
	public final void setString1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String string1)
	{
		getMendixObject().setValue(context, MemberNames.String1.toString(), string1);
	}

	/**
	 * @return value of String2
	 */
	public final java.lang.String getString2()
	{
		return getString2(getContext());
	}

	/**
	 * @param context
	 * @return value of String2
	 */
	public final java.lang.String getString2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.String2.toString());
	}

	/**
	 * Set value of String2
	 * @param string2
	 */
	public final void setString2(java.lang.String string2)
	{
		setString2(getContext(), string2);
	}

	/**
	 * Set value of String2
	 * @param context
	 * @param string2
	 */
	public final void setString2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String string2)
	{
		getMendixObject().setValue(context, MemberNames.String2.toString(), string2);
	}

	/**
	 * Set value of LevenshteinType
	 * @param levenshteintype
	 */
	public final fastestlevenshtein.proxies.ENUM_LevenshteinType getLevenshteinType()
	{
		return getLevenshteinType(getContext());
	}

	/**
	 * @param context
	 * @return value of LevenshteinType
	 */
	public final fastestlevenshtein.proxies.ENUM_LevenshteinType getLevenshteinType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.LevenshteinType.toString());
		if (obj == null) {
			return null;
		}
		return fastestlevenshtein.proxies.ENUM_LevenshteinType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of LevenshteinType
	 * @param levenshteintype
	 */
	public final void setLevenshteinType(fastestlevenshtein.proxies.ENUM_LevenshteinType levenshteintype)
	{
		setLevenshteinType(getContext(), levenshteintype);
	}

	/**
	 * Set value of LevenshteinType
	 * @param context
	 * @param levenshteintype
	 */
	public final void setLevenshteinType(com.mendix.systemwideinterfaces.core.IContext context, fastestlevenshtein.proxies.ENUM_LevenshteinType levenshteintype)
	{
		if (levenshteintype != null) {
			getMendixObject().setValue(context, MemberNames.LevenshteinType.toString(), levenshteintype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.LevenshteinType.toString(), null);
		}
	}

	/**
	 * @return value of Distance
	 */
	public final java.lang.Long getDistance()
	{
		return getDistance(getContext());
	}

	/**
	 * @param context
	 * @return value of Distance
	 */
	public final java.lang.Long getDistance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Distance.toString());
	}

	/**
	 * Set value of Distance
	 * @param distance
	 */
	public final void setDistance(java.lang.Long distance)
	{
		setDistance(getContext(), distance);
	}

	/**
	 * Set value of Distance
	 * @param context
	 * @param distance
	 */
	public final void setDistance(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long distance)
	{
		getMendixObject().setValue(context, MemberNames.Distance.toString(), distance);
	}

	/**
	 * @return value of Closest
	 */
	public final java.lang.String getClosest()
	{
		return getClosest(getContext());
	}

	/**
	 * @param context
	 * @return value of Closest
	 */
	public final java.lang.String getClosest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Closest.toString());
	}

	/**
	 * Set value of Closest
	 * @param closest
	 */
	public final void setClosest(java.lang.String closest)
	{
		setClosest(getContext(), closest);
	}

	/**
	 * Set value of Closest
	 * @param context
	 * @param closest
	 */
	public final void setClosest(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String closest)
	{
		getMendixObject().setValue(context, MemberNames.Closest.toString(), closest);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return levenshteinMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fastestlevenshtein.proxies.Levenshtein that = (fastestlevenshtein.proxies.Levenshtein) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
